project_id = "vmdkqowhjqypnbaxtbkg"

[functions.google-analytics]
enabled = true
verify_jwt = false
import_map = "./functions/google-analytics/deno.json"
entrypoint = "./functions/google-analytics/index.ts"

[functions.razorpay]
enabled = true
verify_jwt = false
supabase functions deploy razorpay