/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WhyChooseUsRouteImport } from './routes/why-choose-us'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ToolsCodeRouteImport } from './routes/tools.code'
import { Route as ToolsColorRouteImport } from './routes/tools.color'
import { Route as ToolsImageRouteImport } from './routes/tools.image'
import { Route as ToolsPasswordRouteImport } from './routes/tools.password'
import { Route as ToolsPdfRouteImport } from './routes/tools.pdf'
import { Route as ToolsProductivityRouteImport } from './routes/tools.productivity'
import { Route as ToolsTextRouteImport } from './routes/tools.text'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'
import { Route as AuthenticatedAdminProfileRouteImport } from './routes/_authenticated/_admin/profile'
import { Route as ApiAdminExportAuditLogsRouteImport } from './routes/api/admin/export.audit-logs'
import { Route as ApiAdminExportToolUsageRouteImport } from './routes/api/admin/export.tool-usage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyChooseUsRoute = WhyChooseUsRouteImport.update({
  id: '/why-choose-us',
  path: '/why-choose-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ToolsCodeRoute = ToolsCodeRouteImport.update({
  id: '/tools/code',
  path: '/tools/code',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsColorRoute = ToolsColorRouteImport.update({
  id: '/tools/color',
  path: '/tools/color',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageRoute = ToolsImageRouteImport.update({
  id: '/tools/image',
  path: '/tools/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPasswordRoute = ToolsPasswordRouteImport.update({
  id: '/tools/password',
  path: '/tools/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfRoute = ToolsPdfRouteImport.update({
  id: '/tools/pdf',
  path: '/tools/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsProductivityRoute = ToolsProductivityRouteImport.update({
  id: '/tools/productivity',
  path: '/tools/productivity',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTextRoute = ToolsTextRouteImport.update({
  id: '/tools/text',
  path: '/tools/text',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProfileRoute =
  AuthenticatedAdminProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiAdminExportAuditLogsRoute = ApiAdminExportAuditLogsRouteImport.update({
  id: '/api/admin/export/audit-logs',
  path: '/api/admin/export/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminExportToolUsageRoute = ApiAdminExportToolUsageRouteImport.update({
  id: '/api/admin/export/tool-usage',
  path: '/api/admin/export/tool-usage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tools/code': typeof ToolsCodeRoute
  '/tools/color': typeof ToolsColorRoute
  '/tools/image': typeof ToolsImageRoute
  '/tools/password': typeof ToolsPasswordRoute
  '/tools/pdf': typeof ToolsPdfRoute
  '/tools/productivity': typeof ToolsProductivityRoute
  '/tools/text': typeof ToolsTextRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/profile': typeof AuthenticatedAdminProfileRoute
  '/api/admin/export/audit-logs': typeof ApiAdminExportAuditLogsRoute
  '/api/admin/export/tool-usage': typeof ApiAdminExportToolUsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tools/code': typeof ToolsCodeRoute
  '/tools/color': typeof ToolsColorRoute
  '/tools/image': typeof ToolsImageRoute
  '/tools/password': typeof ToolsPasswordRoute
  '/tools/pdf': typeof ToolsPdfRoute
  '/tools/productivity': typeof ToolsProductivityRoute
  '/tools/text': typeof ToolsTextRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/profile': typeof AuthenticatedAdminProfileRoute
  '/api/admin/export/audit-logs': typeof ApiAdminExportAuditLogsRoute
  '/api/admin/export/tool-usage': typeof ApiAdminExportToolUsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/tools/code': typeof ToolsCodeRoute
  '/tools/color': typeof ToolsColorRoute
  '/tools/image': typeof ToolsImageRoute
  '/tools/password': typeof ToolsPasswordRoute
  '/tools/pdf': typeof ToolsPdfRoute
  '/tools/productivity': typeof ToolsProductivityRoute
  '/tools/text': typeof ToolsTextRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRoute
  '/_authenticated/_admin/profile': typeof AuthenticatedAdminProfileRoute
  '/api/admin/export/audit-logs': typeof ApiAdminExportAuditLogsRoute
  '/api/admin/export/tool-usage': typeof ApiAdminExportToolUsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/favorites'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/why-choose-us'
    | '/dashboard'
    | '/tools/code'
    | '/tools/color'
    | '/tools/image'
    | '/tools/password'
    | '/tools/pdf'
    | '/tools/productivity'
    | '/tools/text'
    | '/admin'
    | '/profile'
    | '/api/admin/export/audit-logs'
    | '/api/admin/export/tool-usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/favorites'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/why-choose-us'
    | '/dashboard'
    | '/tools/code'
    | '/tools/color'
    | '/tools/image'
    | '/tools/password'
    | '/tools/pdf'
    | '/tools/productivity'
    | '/tools/text'
    | '/admin'
    | '/profile'
    | '/api/admin/export/audit-logs'
    | '/api/admin/export/tool-usage'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/favorites'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/why-choose-us'
    | '/_authenticated/_admin'
    | '/_authenticated/dashboard'
    | '/tools/code'
    | '/tools/color'
    | '/tools/image'
    | '/tools/password'
    | '/tools/pdf'
    | '/tools/productivity'
    | '/tools/text'
    | '/_authenticated/_admin/admin'
    | '/_authenticated/_admin/profile'
    | '/api/admin/export/audit-logs'
    | '/api/admin/export/tool-usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WhyChooseUsRoute: typeof WhyChooseUsRoute
  ToolsCodeRoute: typeof ToolsCodeRoute
  ToolsColorRoute: typeof ToolsColorRoute
  ToolsImageRoute: typeof ToolsImageRoute
  ToolsPasswordRoute: typeof ToolsPasswordRoute
  ToolsPdfRoute: typeof ToolsPdfRoute
  ToolsProductivityRoute: typeof ToolsProductivityRoute
  ToolsTextRoute: typeof ToolsTextRoute
  ApiAdminExportAuditLogsRoute: typeof ApiAdminExportAuditLogsRoute
  ApiAdminExportToolUsageRoute: typeof ApiAdminExportToolUsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-choose-us': {
      id: '/why-choose-us'
      path: '/why-choose-us'
      fullPath: '/why-choose-us'
      preLoaderRoute: typeof WhyChooseUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/tools/code': {
      id: '/tools/code'
      path: '/tools/code'
      fullPath: '/tools/code'
      preLoaderRoute: typeof ToolsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/color': {
      id: '/tools/color'
      path: '/tools/color'
      fullPath: '/tools/color'
      preLoaderRoute: typeof ToolsColorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image': {
      id: '/tools/image'
      path: '/tools/image'
      fullPath: '/tools/image'
      preLoaderRoute: typeof ToolsImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/password': {
      id: '/tools/password'
      path: '/tools/password'
      fullPath: '/tools/password'
      preLoaderRoute: typeof ToolsPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf': {
      id: '/tools/pdf'
      path: '/tools/pdf'
      fullPath: '/tools/pdf'
      preLoaderRoute: typeof ToolsPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/productivity': {
      id: '/tools/productivity'
      path: '/tools/productivity'
      fullPath: '/tools/productivity'
      preLoaderRoute: typeof ToolsProductivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/text': {
      id: '/tools/text'
      path: '/tools/text'
      fullPath: '/tools/text'
      preLoaderRoute: typeof ToolsTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/profile': {
      id: '/_authenticated/_admin/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedAdminProfileRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/admin/export/audit-logs': {
      id: '/api/admin/export/audit-logs'
      path: '/api/admin/export/audit-logs'
      fullPath: '/api/admin/export/audit-logs'
      preLoaderRoute: typeof ApiAdminExportAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/export/tool-usage': {
      id: '/api/admin/export/tool-usage'
      path: '/api/admin/export/tool-usage'
      fullPath: '/api/admin/export/tool-usage'
      preLoaderRoute: typeof ApiAdminExportToolUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRoute
  AuthenticatedAdminProfileRoute: typeof AuthenticatedAdminProfileRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRoute,
  AuthenticatedAdminProfileRoute: AuthenticatedAdminProfileRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WhyChooseUsRoute: WhyChooseUsRoute,
  ToolsCodeRoute: ToolsCodeRoute,
  ToolsColorRoute: ToolsColorRoute,
  ToolsImageRoute: ToolsImageRoute,
  ToolsPasswordRoute: ToolsPasswordRoute,
  ToolsPdfRoute: ToolsPdfRoute,
  ToolsProductivityRoute: ToolsProductivityRoute,
  ToolsTextRoute: ToolsTextRoute,
  ApiAdminExportAuditLogsRoute: ApiAdminExportAuditLogsRoute,
  ApiAdminExportToolUsageRoute: ApiAdminExportToolUsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
